import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { CalendarDays, CheckCircle2, Clock3, DollarSign, LogOut, Menu, User, X } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { signOut } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import type { Appointment, BusinessNotification, BusinessTask, Employee, EmployeeShift, TimeEntry, TimeOffRequest } from '@/lib/supabase';
import { money } from '@/lib/data';

const card: React.CSSProperties = { background:'#111',color:'#fff',border:'1px solid #292929',borderRadius:14,padding:20 };
const dt=(v?:string|null)=>v?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const day=(v?:string|null)=>v?new Date(`${v}T12:00:00`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'}):'—';

type Tab='today'|'schedule'|'timeclock'|'pay'|'timeoff'|'tasks';

export default function EmployeePortal(){
  const {user,profile,loading}=useAuth(); const navigate=useNavigate(); const [tab,setTab]=useState<Tab>('today'); const [sidebarOpen,setSidebarOpen]=useState(false);
  const [employee,setEmployee]=useState<Employee|null>(null); const [jobs,setJobs]=useState<Appointment[]>([]); const [shifts,setShifts]=useState<EmployeeShift[]>([]); const [times,setTimes]=useState<TimeEntry[]>([]); const [tasks,setTasks]=useState<BusinessTask[]>([]); const [off,setOff]=useState<TimeOffRequest[]>([]); const [notifications,setNotifications]=useState<BusinessNotification[]>([]); const [dataLoading,setDataLoading]=useState(true);
  const [timeOffForm,setTimeOffForm]=useState({start_date:'',end_date:'',request_type:'unpaid',reason:''});

  useEffect(()=>{if(!loading&&(!user||!['employee','manager','d2d','owner'].includes(profile?.portal_role||'')))navigate('/portal')},[user,profile,loading,navigate]);
  useEffect(()=>{if(!user)return;(async()=>{const {data:emp}=await supabase.from('employees').select('*').eq('user_id',user.id).maybeSingle();setEmployee(emp);if(!emp){setDataLoading(false);return;}const [j,s,t,tk,o,n]=await Promise.all([supabase.from('appointments').select('*').eq('assigned_employee_id',emp.id).order('scheduled_at'),supabase.from('employee_shifts').select('*').eq('employee_id',emp.id).order('shift_date'),supabase.from('time_entries').select('*').eq('employee_id',emp.id).order('clock_in',{ascending:false}),supabase.from('business_tasks').select('*').eq('assigned_employee_id',emp.id).order('due_at'),supabase.from('time_off_requests').select('*').eq('employee_id',emp.id).order('created_at',{ascending:false}),supabase.from('business_notifications').select('*').or(`target_employee_id.eq.${emp.id},target_user_id.eq.${user.id},target_portal_role.eq.employee`).order('created_at',{ascending:false}).limit(20)]);setJobs(j.data??[]);setShifts(s.data??[]);setTimes(t.data??[]);setTasks(tk.data??[]);setOff(o.data??[]);setNotifications(n.data??[]);setDataLoading(false);})()},[user]);

  const openEntry=times.find(t=>!t.clock_out);
  const clockIn=async()=>{if(!employee||openEntry)return;const {data,error}=await supabase.from('time_entries').insert({employee_id:employee.id,clock_in:new Date().toISOString(),status:'pending'}).select().single();if(error)return alert(error.message);setTimes(p=>[data,...p]);};
  const clockOut=async()=>{if(!openEntry)return;const {data,error}=await supabase.from('time_entries').update({clock_out:new Date().toISOString()}).eq('id',openEntry.id).select().single();if(error)return alert(error.message);setTimes(p=>p.map(t=>t.id===openEntry.id?data:t));};
  const hours=(t:TimeEntry)=>t.clock_out?Math.max(0,(new Date(t.clock_out).getTime()-new Date(t.clock_in).getTime())/3600000-(t.break_minutes||0)/60):0;
  const weekStart=useMemo(()=>{const d=new Date();d.setDate(d.getDate()-d.getDay());d.setHours(0,0,0,0);return d},[]);
  const weekHours=times.filter(t=>new Date(t.clock_in)>=weekStart).reduce((s,t)=>s+hours(t),0); const estPay=weekHours*Number(employee?.hourly_rate||0);
  const requestOff=async(e:React.FormEvent)=>{e.preventDefault();if(!employee)return;const {data,error}=await supabase.from('time_off_requests').insert({...timeOffForm,employee_id:employee.id,status:'pending'}).select().single();if(error)return alert(error.message);setOff(p=>[data,...p]);setTimeOffForm({start_date:'',end_date:'',request_type:'unpaid',reason:''})};
  const logout=async()=>{await signOut().catch(()=>{});navigate('/')};
  if(loading||dataLoading)return <div className="portal-loading"><div className="portal-spinner"/><p>Loading employee portal...</p></div>;
  if(!employee)return <div className="portal-loading"><p>Your login is not linked to an employee record yet. Ask an owner to link your account in Admin → Permissions.</p><Link to="/">Home</Link></div>;
  const nav:[Tab,string,any][]=[['today','My Jobs',User],['schedule','My Schedule',CalendarDays],['timeclock','Time Clock',Clock3],['pay','Pay Estimate',DollarSign],['timeoff','Time Off',CalendarDays],['tasks','My Tasks',CheckCircle2]];
  const today=new Date().toISOString().slice(0,10); const todayJobs=jobs.filter(j=>j.scheduled_at?.slice(0,10)===today&&j.status!=='cancelled');
  return <div className="portal-layout"><aside className={`portal-sidebar ${sidebarOpen?'sidebar-open':''}`}><div className="sidebar-header"><Link to="/" className="sidebar-brand"><div className="brand-mark brand-mark-sm">NS</div><div><strong>EMPLOYEE</strong><small>NORTH SPLASH</small></div></Link><button className="sidebar-close" onClick={()=>setSidebarOpen(false)}><X size={18}/></button></div><div className="sidebar-user"><div className="sidebar-avatar">{employee.name[0]}</div><div><p>{employee.name}</p><span>{employee.role.replaceAll('_',' ')} · Level {employee.employment_level||1}</span></div></div><nav className="sidebar-nav">{nav.map(([id,label,Icon])=><button key={id} className={`sidebar-item ${tab===id?'sidebar-active':''}`} onClick={()=>{setTab(id);setSidebarOpen(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-footer"><button className="sidebar-item sidebar-signout" onClick={logout}><LogOut size={18}/> Sign Out</button></div></aside>{sidebarOpen&&<div className="sidebar-backdrop" onClick={()=>setSidebarOpen(false)}/>}<main className="portal-main"><div className="portal-topbar"><button className="sidebar-toggle" onClick={()=>setSidebarOpen(true)}><Menu size={20}/></button><div className="topbar-title"><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div></div><div className="portal-content">
    {notifications.filter(n=>!n.read_at).slice(0,3).map(n=><div key={n.id} style={{...card,marginBottom:10,borderColor:'#5c4d2b'}}><strong>{n.title}</strong><p>{n.message}</p></div>)}
    {tab==='today'&&<div className="tab-content"><div className="tab-header"><div><h2>Today's Assigned Jobs</h2><p>{todayJobs.length} jobs assigned today</p></div></div><div style={{display:'grid',gap:12}}>{todayJobs.map(j=><div style={card} key={j.id}><div style={{display:'flex',justifyContent:'space-between'}}><div><strong>{j.service_name}</strong><p>{j.vehicle_info||'Vehicle not listed'}</p></div><span>{dt(j.scheduled_at)}</span></div><p>{j.notes}</p><select value={j.status} onChange={async e=>{const status=e.target.value;await supabase.from('appointments').update({status}).eq('id',j.id);setJobs(p=>p.map(x=>x.id===j.id?{...x,status:status as any}:x));}}><option value="confirmed">Confirmed</option><option value="in_progress">In Progress</option><option value="completed">Completed</option></select></div>)}{todayJobs.length===0&&<div style={card}>No assigned jobs today.</div>}</div></div>}
    {tab==='schedule'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{shifts.map(s=><div style={card} key={s.id}><strong>{day(s.shift_date)}</strong><p>{s.start_time?.slice(0,5)} – {s.end_time?.slice(0,5)} · {s.status}</p><small>{s.notes}</small></div>)}</div></div>}
    {tab==='timeclock'&&<div className="tab-content"><div style={{...card,maxWidth:560}}><h2>{openEntry?'You are clocked in':'Ready to start?'}</h2>{openEntry?<><p>Clocked in {dt(openEntry.clock_in)}</p><button className="btn-primary btn-full" onClick={clockOut}>Clock Out</button></>:<button className="btn-primary btn-full" onClick={clockIn}>Clock In</button>}</div><div style={{...card,marginTop:18}}><h3>Recent Timecards</h3>{times.slice(0,12).map(t=><div className="admin-row" key={t.id}><div className="admin-row-main"><strong>{dt(t.clock_in)}</strong><span>{t.clock_out?`${hours(t).toFixed(2)} hours`:'Open shift'}</span></div><span>{t.status}</span></div>)}</div></div>}
    {tab==='pay'&&<div className="tab-content"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}><div style={card}><span>This Week Hours</span><h2>{weekHours.toFixed(2)}</h2></div><div style={card}><span>Current Rate</span><h2>{money(Number(employee.hourly_rate||0))}/hr</h2></div><div style={card}><span>Estimated Gross Pay</span><h2>{money(estPay)}</h2></div></div><p style={{color:'#888'}}>Estimate only. Approved payroll, taxes and deductions may differ.</p></div>}
    {tab==='timeoff'&&<div className="tab-content"><form style={{...card,marginBottom:18}} onSubmit={requestOff}><h3>Request Time Off</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10}}><input required type="date" value={timeOffForm.start_date} onChange={e=>setTimeOffForm(p=>({...p,start_date:e.target.value}))}/><input required type="date" value={timeOffForm.end_date} onChange={e=>setTimeOffForm(p=>({...p,end_date:e.target.value}))}/><select value={timeOffForm.request_type} onChange={e=>setTimeOffForm(p=>({...p,request_type:e.target.value}))}><option value="unpaid">Unpaid</option><option value="pto">PTO</option><option value="sick">Sick</option></select></div><textarea placeholder="Reason" value={timeOffForm.reason} onChange={e=>setTimeOffForm(p=>({...p,reason:e.target.value}))}/><button className="btn-primary">Submit Request</button></form>{off.map(r=><div style={card} key={r.id}><strong>{day(r.start_date)} → {day(r.end_date)}</strong><p>{r.reason}</p><span>{r.status}</span></div>)}</div>}
    {tab==='tasks'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{tasks.map(t=><div style={card} key={t.id}><strong>{t.title}</strong><p>{t.description}</p><small>Due {dt(t.due_at)} · {t.priority}</small><div><select value={t.status} onChange={async e=>{const status=e.target.value;await supabase.from('business_tasks').update({status,completed_at:status==='completed'?new Date().toISOString():null}).eq('id',t.id);setTasks(p=>p.map(x=>x.id===t.id?{...x,status}:x));}}><option>open</option><option>in_progress</option><option>blocked</option><option>completed</option></select></div></div>)}</div></div>}
  </div></main></div>;
}
