-- North Splash Field Operations expansion: polygon territories, door canvassing,
-- detailer map statuses, dispatch/QC, service checklists, incidents and operational records.
ALTER TABLE public.lead_territories ADD COLUMN IF NOT EXISTS polygon_geojson jsonb, ADD COLUMN IF NOT EXISTS start_date date, ADD COLUMN IF NOT EXISTS end_date date, ADD COLUMN IF NOT EXISTS team_name text;
ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS service_address text, ADD COLUMN IF NOT EXISTS latitude numeric, ADD COLUMN IF NOT EXISTS longitude numeric, ADD COLUMN IF NOT EXISTS field_status text NOT NULL DEFAULT 'scheduled', ADD COLUMN IF NOT EXISTS cancellation_reason text, ADD COLUMN IF NOT EXISTS qc_status text NOT NULL DEFAULT 'not_required', ADD COLUMN IF NOT EXISTS customer_signature text, ADD COLUMN IF NOT EXISTS tip_amount numeric NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS travel_fee numeric NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS public.territory_doors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), territory_id uuid NOT NULL REFERENCES public.lead_territories(id) ON DELETE CASCADE, lead_id uuid REFERENCES public.leads(id) ON DELETE SET NULL, address text, latitude numeric NOT NULL, longitude numeric NOT NULL, status text NOT NULL DEFAULT 'unworked', last_visited_at timestamptz, last_employee_id uuid REFERENCES public.employees(id) ON DELETE SET NULL, notes text, source text NOT NULL DEFAULT 'map', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS territory_doors_coord_unique ON public.territory_doors(territory_id,latitude,longitude);
CREATE TABLE IF NOT EXISTS public.job_checklist_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), appointment_id uuid NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE, label text NOT NULL, sort_order integer NOT NULL DEFAULT 0, completed boolean NOT NULL DEFAULT false, completed_by uuid REFERENCES public.employees(id) ON DELETE SET NULL, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.job_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), appointment_id uuid NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE, employee_id uuid REFERENCES public.employees(id) ON DELETE SET NULL, media_type text NOT NULL DEFAULT 'before', file_url text NOT NULL, caption text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.incident_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), appointment_id uuid REFERENCES public.appointments(id) ON DELETE SET NULL, employee_id uuid REFERENCES public.employees(id) ON DELETE SET NULL, incident_type text NOT NULL, severity text NOT NULL DEFAULT 'normal', description text NOT NULL, status text NOT NULL DEFAULT 'open', manager_note text, created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz);
CREATE TABLE IF NOT EXISTS public.customer_estimates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid REFERENCES public.leads(id) ON DELETE SET NULL, customer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, employee_id uuid REFERENCES public.employees(id) ON DELETE SET NULL, amount numeric NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'draft', expires_at timestamptz, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.purchase_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), requested_by uuid REFERENCES public.employees(id) ON DELETE SET NULL, item_name text NOT NULL, amount numeric NOT NULL DEFAULT 0, reason text, status text NOT NULL DEFAULT 'pending', approved_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), decided_at timestamptz);
CREATE TABLE IF NOT EXISTS public.training_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE, module_name text NOT NULL, status text NOT NULL DEFAULT 'assigned', score numeric, completed_at timestamptz, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.cash_reconciliations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), employee_id uuid REFERENCES public.employees(id) ON DELETE SET NULL, business_date date NOT NULL DEFAULT current_date, expected_amount numeric NOT NULL DEFAULT 0, deposited_amount numeric NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'open', notes text, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.territory_doors ENABLE ROW LEVEL SECURITY; ALTER TABLE public.job_checklist_items ENABLE ROW LEVEL SECURITY; ALTER TABLE public.job_media ENABLE ROW LEVEL SECURITY; ALTER TABLE public.incident_reports ENABLE ROW LEVEL SECURITY; ALTER TABLE public.customer_estimates ENABLE ROW LEVEL SECURITY; ALTER TABLE public.purchase_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.training_records ENABLE ROW LEVEL SECURITY; ALTER TABLE public.cash_reconciliations ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.territory_doors,public.job_checklist_items,public.job_media,public.incident_reports,public.customer_estimates,public.purchase_requests,public.training_records,public.cash_reconciliations TO authenticated;
DROP POLICY IF EXISTS territory_doors_staff ON public.territory_doors; CREATE POLICY territory_doors_staff ON public.territory_doors FOR ALL TO authenticated USING (public.has_permission('territories.manage') OR EXISTS(SELECT 1 FROM public.lead_territories t WHERE t.id=territory_id AND t.assigned_employee_id=public.current_employee_id())) WITH CHECK (public.has_permission('territories.manage') OR EXISTS(SELECT 1 FROM public.lead_territories t WHERE t.id=territory_id AND t.assigned_employee_id=public.current_employee_id()));
DROP POLICY IF EXISTS checklist_assigned ON public.job_checklist_items; CREATE POLICY checklist_assigned ON public.job_checklist_items FOR ALL TO authenticated USING (public.has_permission('appointments.manage') OR EXISTS(SELECT 1 FROM public.appointments a WHERE a.id=appointment_id AND (a.assigned_employee_id=public.current_employee_id() OR a.assigned_manager_id=public.current_employee_id()))) WITH CHECK (public.has_permission('appointments.manage') OR EXISTS(SELECT 1 FROM public.appointments a WHERE a.id=appointment_id AND (a.assigned_employee_id=public.current_employee_id() OR a.assigned_manager_id=public.current_employee_id())));
DROP POLICY IF EXISTS media_assigned ON public.job_media; CREATE POLICY media_assigned ON public.job_media FOR ALL TO authenticated USING (public.has_permission('appointments.manage') OR employee_id=public.current_employee_id()) WITH CHECK (public.has_permission('appointments.manage') OR employee_id=public.current_employee_id());
DROP POLICY IF EXISTS incidents_staff ON public.incident_reports; CREATE POLICY incidents_staff ON public.incident_reports FOR ALL TO authenticated USING (public.has_permission('appointments.manage') OR employee_id=public.current_employee_id()) WITH CHECK (public.has_permission('appointments.manage') OR employee_id=public.current_employee_id());
DROP POLICY IF EXISTS estimates_staff ON public.customer_estimates; CREATE POLICY estimates_staff ON public.customer_estimates FOR ALL TO authenticated USING (public.has_permission('sales.manage') OR employee_id=public.current_employee_id()) WITH CHECK (public.has_permission('sales.manage') OR employee_id=public.current_employee_id());
DROP POLICY IF EXISTS purchases_staff ON public.purchase_requests; CREATE POLICY purchases_staff ON public.purchase_requests FOR ALL TO authenticated USING (public.has_permission('inventory.manage') OR requested_by=public.current_employee_id()) WITH CHECK (public.has_permission('inventory.manage') OR requested_by=public.current_employee_id());
DROP POLICY IF EXISTS training_staff ON public.training_records; CREATE POLICY training_staff ON public.training_records FOR SELECT TO authenticated USING (public.has_permission('employees.view') OR employee_id=public.current_employee_id());
DROP POLICY IF EXISTS cash_staff ON public.cash_reconciliations; CREATE POLICY cash_staff ON public.cash_reconciliations FOR ALL TO authenticated USING (public.has_permission('finance.manage') OR employee_id=public.current_employee_id()) WITH CHECK (public.has_permission('finance.manage') OR employee_id=public.current_employee_id());
