import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Client-Info, Apikey','Content-Type':'application/json'};
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const token=(req.headers.get('Authorization')||'').replace('Bearer ','');const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const {data:{user}}=await admin.auth.getUser(token);if(!user)throw new Error('Unauthorized');
 const body=await req.json();const lat=Number(body.latitude),lng=Number(body.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))throw new Error('Valid latitude and longitude are required.');
 const key=`${lat.toFixed(5)},${lng.toFixed(5)}`;const {data:cached}=await admin.from('geocode_cache').select('*').eq('cache_key',key).maybeSingle();if(cached)return json({success:true,cached:true,...cached.payload});
 const url=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}&zoom=18&addressdetails=1`;const r=await fetch(url,{headers:{'Accept-Language':'en-US,en','User-Agent':'NorthSplashAutoLuxe/1.0 (admin@northsplash.com)'}});if(!r.ok)throw new Error(`Address lookup failed (${r.status}).`);const d=await r.json();const a=d.address||{};const street=[a.house_number,a.road||a.residential||a.pedestrian].filter(Boolean).join(' ');const city=a.city||a.town||a.village||a.municipality||'';const state=a.state||'';const postal_code=a.postcode||'';const address=[street,[city,state,postal_code].filter(Boolean).join(', ').replace(/, ([0-9]{5})$/,' $1')].filter(Boolean).join(', ')||d.display_name||'';const payload={address,street,house_number:a.house_number||'',city,state,postal_code,display_name:d.display_name||address};await admin.from('geocode_cache').upsert({cache_key:key,latitude:lat,longitude:lng,payload},{onConflict:'cache_key'});return json({success:true,cached:false,...payload});
}catch(e){return json({error:e instanceof Error?e.message:String(e)},400)}});
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors})}
