-- North Splash OS expansion tables. Run after existing Enterprise + Field Operations SQL.
create extension if not exists pgcrypto;
create table if not exists public.business_locations (id uuid primary key default gen_random_uuid(),name text not null,city text,state text,manager_name text,service_radius numeric default 25,status text default 'active',created_at timestamptz default now());
create table if not exists public.fleet_accounts (id uuid primary key default gen_random_uuid(),company_name text not null,contact_name text,email text,phone text,vehicle_count int default 0,billing_terms text,status text default 'active',created_at timestamptz default now());
create table if not exists public.marketing_campaigns (id uuid primary key default gen_random_uuid(),name text not null,channel text,budget numeric default 0,start_date date,end_date date,status text default 'active',created_at timestamptz default now());
create table if not exists public.automation_rules (id uuid primary key default gen_random_uuid(),name text not null,trigger_event text,action_type text,delay_minutes int default 0,is_enabled boolean default true,created_at timestamptz default now());
create table if not exists public.incident_reports (id uuid primary key default gen_random_uuid(),title text not null,incident_type text,employee_name text,appointment_ref text,description text,status text default 'open',created_at timestamptz default now());
create table if not exists public.training_courses (id uuid primary key default gen_random_uuid(),title text not null,category text,required_role text,renewal_months int,status text default 'active',created_at timestamptz default now());
create table if not exists public.purchase_requests (id uuid primary key default gen_random_uuid(),item_name text not null,vendor text,amount numeric default 0,requested_by text,reason text,status text default 'pending',created_at timestamptz default now());
create table if not exists public.communication_templates (id uuid primary key default gen_random_uuid(),name text not null,channel text,event_key text,subject text,body text,status text default 'active',created_at timestamptz default now());
create table if not exists public.retention_campaigns (id uuid primary key default gen_random_uuid(),name text not null,days_inactive int default 90,offer text,status text default 'active',created_at timestamptz default now());
create table if not exists public.data_exports (id uuid primary key default gen_random_uuid(),name text not null,scope text,status text default 'requested',notes text,created_at timestamptz default now());
-- RLS: authenticated users can read; writes are constrained in the app by portal permissions. Tighten policies further before delegating owner privileges broadly.
do $$ declare t text; begin foreach t in array array['business_locations','fleet_accounts','marketing_campaigns','automation_rules','incident_reports','training_courses','purchase_requests','communication_templates','retention_campaigns','data_exports'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists authenticated_read on public.%I',t); execute format('create policy authenticated_read on public.%I for select to authenticated using (true)',t); execute format('drop policy if exists authenticated_write on public.%I',t); execute format('create policy authenticated_write on public.%I for all to authenticated using (true) with check (true)',t); end loop; end $$;
