import { useEffect, useState } from 'react';
import { Building2, CarFront, Megaphone, Repeat2, ShieldAlert, GraduationCap, ShoppingCart, ClipboardSignature, Sparkles, WalletCards, Workflow, Headphones, DatabaseBackup } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { money } from '@/lib/data';
import type { Appointment, Employee, Profile } from '@/lib/supabase';

export type ExpansionSection='command_center'|'crm'|'dispatch'|'fleet'|'locations'|'marketing'|'automations'|'approvals'|'incidents'|'training'|'purchasing'|'communications'|'retention'|'continuity';
type Props={section:ExpansionSection;employees:Employee[];appointments:Appointment[];customers:Profile[];payments:any[]};
const card:React.CSSProperties={background:'#fffdf9',color:'#211811',border:'1px solid #e3d6ca',borderRadius:18,padding:20,boxShadow:'0 12px 34px rgba(48,32,21,.055)'};
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:14};
const Header=({title,sub}:{title:string;sub:string})=><div className="tab-header ops-header"><div><span className="eyebrow">NORTH SPLASH OS</span><h2>{title}</h2><p>{sub}</p></div></div>;
const Metric=({label,value,detail}:{label:string;value:string;detail?:string})=><div className="ops-metric"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;
const Field=({label,children}:{label:string;children:any})=><label className="ops-field"><span>{label}</span>{children}</label>;

export default function OperationsExpansion({section,employees,appointments,customers,payments}:Props){
 const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [form,setForm]=useState<Record<string,string>>({});
 const cfg:any={
  locations:{table:'business_locations',title:'Locations & Expansion',sub:'Operate Raleigh now and add future cities without rebuilding the platform.',icon:Building2,fields:[['name','Location name'],['city','City'],['state','State'],['manager_name','Manager'],['service_radius','Service radius (miles)']]},
  fleet:{table:'fleet_accounts',title:'Fleet & Commercial Accounts',sub:'Manage dealerships, rental fleets and recurring commercial clients.',icon:CarFront,fields:[['company_name','Company'],['contact_name','Contact'],['email','Email'],['phone','Phone'],['vehicle_count','Vehicle count'],['billing_terms','Billing terms']]},
  marketing:{table:'marketing_campaigns',title:'Marketing & Attribution',sub:'Track campaign spend from source through booked and collected revenue.',icon:Megaphone,fields:[['name','Campaign'],['channel','Channel'],['budget','Budget'],['start_date','Start date'],['end_date','End date']]},
  automations:{table:'automation_rules',title:'Automation Rules',sub:'Create operational triggers without changing application code.',icon:Workflow,fields:[['name','Rule name'],['trigger_event','When this happens'],['action_type','Do this'],['delay_minutes','Delay (minutes)']]},
  incidents:{table:'incident_reports',title:'Incidents & Damage Reports',sub:'Document vehicle/property incidents, safety issues and manager follow-up.',icon:ShieldAlert,fields:[['title','Incident title'],['incident_type','Type'],['employee_name','Employee'],['appointment_ref','Appointment'],['description','Description']]},
  training:{table:'training_courses',title:'Training Center',sub:'Onboarding, detailing procedures, sales training and certification tracking.',icon:GraduationCap,fields:[['title','Course / certification'],['category','Category'],['required_role','Required role'],['renewal_months','Renewal months']]},
  purchasing:{table:'purchase_requests',title:'Purchasing & Approvals',sub:'Request supplies and equipment before money is spent.',icon:ShoppingCart,fields:[['item_name','Item'],['vendor','Vendor'],['amount','Amount'],['requested_by','Requested by'],['reason','Reason']]},
  communications:{table:'communication_templates',title:'Communication Center',sub:'Central templates for booking, en-route, completion, review and follow-up messages.',icon:Headphones,fields:[['name','Template name'],['channel','Email / SMS'],['event_key','Event'],['subject','Subject'],['body','Message']]},
  retention:{table:'retention_campaigns',title:'Retention & Referrals',sub:'Bring customers back, track referrals and schedule service-due follow-ups.',icon:Repeat2,fields:[['name','Campaign'],['days_inactive','Days inactive'],['offer','Offer / message'],['status','Status']]},
  continuity:{table:'data_exports',title:'Business Continuity',sub:'Track exports, backups and recovery checks so company data is portable.',icon:DatabaseBackup,fields:[['name','Export / backup name'],['scope','Data scope'],['status','Status'],['notes','Notes']]},
 };
 const active=cfg[section];
 useEffect(()=>{if(!active){setRows([]);return;}setBusy(true);supabase.from(active.table).select('*').order('created_at',{ascending:false}).limit(100).then(({data})=>{setRows(data??[]);setBusy(false)})},[section]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();if(!active)return;const payload:any={...form};['budget','amount','vehicle_count','delay_minutes','days_inactive','renewal_months','service_radius'].forEach(k=>{if(payload[k]!==undefined&&payload[k]!=='')payload[k]=Number(payload[k])});const {data,error}=await supabase.from(active.table).insert(payload).select().single();if(error)return alert(error.message);setRows(p=>[data,...p]);setForm({})};
 const today=new Date().toISOString().slice(0,10);const activeEmployees=employees.filter(e=>e.status==='active').length;const todayJobs=appointments.filter(a=>a.scheduled_at?.slice(0,10)===today&&a.status!=='cancelled');const collected=payments.filter(p=>p.status==='completed').reduce((s,p)=>s+Number(p.amount||0),0);
 const projected=todayJobs.reduce((s,a)=>s+Number(a.price||0),0);const completed=appointments.filter(a=>a.status==='completed').length;
 if(section==='command_center')return <div className="tab-content"><Header title="Owner Command Center" sub="One screen for the health of the company, today's operation and items that need attention."/><div className="ops-hero"><div><span className="eyebrow">TODAY</span><h2>{todayJobs.length} jobs · {money(projected)} scheduled</h2><p>North Splash operational snapshot</p></div><Sparkles size={32}/></div><div className="ops-metrics"><Metric label="Active Team" value={String(activeEmployees)}/><Metric label="Customers" value={String(customers.length)}/><Metric label="Lifetime Collected" value={money(collected)}/><Metric label="Completed Jobs" value={String(completed)}/><Metric label="Today's Capacity" value={`${todayJobs.length} jobs`}/><Metric label="Projected Today" value={money(projected)}/></div><div style={grid}><div style={card}><h3>Today's Run</h3>{todayJobs.slice(0,8).map(a=><div className="ops-line" key={a.id}><span>{a.service_name}</span><strong>{a.scheduled_at?new Date(a.scheduled_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Unscheduled'}</strong></div>)}{!todayJobs.length&&<p>No jobs scheduled today.</p>}</div><div style={card}><h3>Attention Queue</h3><div className="ops-line"><span>Unassigned appointments</span><strong>{appointments.filter(a=>!a.assigned_employee_id&&!['completed','cancelled'].includes(a.status)).length}</strong></div><div className="ops-line"><span>Pending appointments</span><strong>{appointments.filter(a=>a.status==='pending').length}</strong></div><div className="ops-line"><span>Inactive employees</span><strong>{employees.filter(e=>e.status!=='active').length}</strong></div></div></div></div>;
 if(section==='crm')return <div className="tab-content"><Header title="Customer CRM" sub="A customer-first view of contact information, vehicles, bookings and lifetime value."/><div className="crm-grid">{customers.map(c=>{const ca=appointments.filter(a=>a.user_id===c.id);const spend=ca.filter(a=>a.status==='completed').reduce((s,a)=>s+Number(a.price||0),0);return <div className="crm-card" key={c.id}><div className="crm-avatar">{(c.full_name||c.email||'C')[0].toUpperCase()}</div><div><h3>{c.full_name||'Customer'}</h3><p>{c.email||'No email'} · {c.phone||'No phone'}</p><div className="crm-pills"><span>{ca.length} bookings</span><span>{money(spend)} lifetime</span></div><small>{c.vehicle_info||'No saved vehicle'}</small></div></div>})}</div></div>;
 if(section==='dispatch')return <div className="tab-content"><Header title="Dispatch Board" sub="Assign today's jobs to crews and move work through the field workflow."/><div className="dispatch-board">{['Unassigned',...employees.filter(e=>e.status==='active'&&['detailer','manager'].includes(e.role)).slice(0,6).map(e=>e.name)].map(name=><div className="dispatch-column" key={name}><h3>{name}</h3>{todayJobs.filter(a=>name==='Unassigned'?!a.assigned_employee_id:employees.find(e=>e.id===a.assigned_employee_id)?.name===name).map(a=><div className="dispatch-job" key={a.id}><strong>{a.service_name}</strong><span>{a.scheduled_at?new Date(a.scheduled_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'No time'}</span><small>{a.service_address||a.vehicle_info||'Address pending'}</small></div>)}</div>)}</div></div>;
 if(section==='approvals')return <div className="tab-content"><Header title="Approvals Center" sub="One inbox for time, PTO, purchases, discounts, incidents and other manager/owner decisions."/><div style={grid}><div style={card}><ClipboardSignature/><h3>Timesheets</h3><p>Review pending timecards from Payroll Approval.</p></div><div style={card}><ShoppingCart/><h3>Purchases</h3><p>Review requests in Purchasing before company funds are spent.</p></div><div style={card}><ShieldAlert/><h3>Incidents</h3><p>Review open incident reports and corrective actions.</p></div><div style={card}><WalletCards/><h3>Financial Controls</h3><p>Keep refunds, discounts and pay changes owner-controlled.</p></div></div></div>;
 if(!active)return null;const Icon=active.icon;return <div className="tab-content"><Header title={active.title} sub={active.sub}/><form className="ops-form" onSubmit={add}><div className="ops-form-title"><Icon size={20}/><strong>Add record</strong></div><div className="ops-form-grid">{active.fields.map(([k,l]:string[])=><Field label={l} key={k}>{k==='description'||k==='body'||k==='notes'||k==='reason'?<textarea value={form[k]||''} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/>:<input type={k.includes('date')?'date':(['budget','amount','vehicle_count','delay_minutes','days_inactive','renewal_months','service_radius'].includes(k)?'number':'text')} value={form[k]||''} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/>}</Field>)}</div><button className="btn-primary">Save</button></form>{busy?<p>Loading…</p>:<div className="ops-record-grid">{rows.map(r=><div className="ops-record" key={r.id}><Icon size={18}/><div><strong>{r.name||r.title||r.company_name||r.item_name||'Record'}</strong><p>{r.city||r.channel||r.category||r.status||r.description||r.scope||'Active record'}</p></div></div>)}{!rows.length&&<div className="ops-empty">No records yet. Add the first one above.</div>}</div>}</div>;
}
