import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, DollarSign, LogOut, Menu, PackageSearch, Target, UserCheck, X } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { signOut } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import type { Appointment, BusinessTask, Employee, EmployeeShift, Lead, RecruitingCandidate, TimeEntry } from '@/lib/supabase';
import { can } from '@/lib/permissions';
import { money } from '@/lib/data';

type Tab='overview'|'jobs'|'schedule'|'timecards'|'recruiting'|'leads'|'tasks'|'inventory'|'finance';
const card:React.CSSProperties={background:'#111',border:'1px solid #292929',borderRadius:14,padding:20,color:'#fff'};
const dt=(v?:string|null)=>v?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
export default function ManagerPortal(){const {user,profile,loading}=useAuth();const navigate=useNavigate();const [tab,setTab]=useState<Tab>('overview');const [sidebar,setSidebar]=useState(false);const [appointments,setAppointments]=useState<Appointment[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [shifts,setShifts]=useState<EmployeeShift[]>([]);const [times,setTimes]=useState<TimeEntry[]>([]);const [candidates,setCandidates]=useState<RecruitingCandidate[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [tasks,setTasks]=useState<BusinessTask[]>([]);const [inventory,setInventory]=useState<any[]>([]);const [payments,setPayments]=useState<any[]>([]);const [expenses,setExpenses]=useState<any[]>([]);const [dataLoading,setDataLoading]=useState(true);
useEffect(()=>{if(!loading&&(!user||!['manager','recruiter','finance','owner'].includes(profile?.portal_role||'')))navigate('/portal')},[user,profile,loading,navigate]);
useEffect(()=>{if(!user)return;(async()=>{const [a,e,s,t,c,l,tk,i,pay,ex]=await Promise.all([supabase.from('appointments').select('*').order('scheduled_at'),supabase.from('employees').select('*').order('name'),supabase.from('employee_shifts').select('*').order('shift_date'),supabase.from('time_entries').select('*').order('clock_in',{ascending:false}).limit(150),supabase.from('recruiting_candidates').select('*').order('created_at',{ascending:false}),supabase.from('leads').select('*').order('created_at',{ascending:false}),supabase.from('business_tasks').select('*').order('due_at'),supabase.from('inventory_items').select('*').order('name'),supabase.from('payments').select('*').order('created_at',{ascending:false}).limit(500),supabase.from('expenses').select('*').order('expense_date',{ascending:false}).limit(500)]);setAppointments(a.data??[]);setEmployees(e.data??[]);setShifts(s.data??[]);setTimes(t.data??[]);setCandidates(c.data??[]);setLeads(l.data??[]);setTasks(tk.data??[]);setInventory(i.data??[]);setPayments(pay.data??[]);setExpenses(ex.data??[]);setDataLoading(false);})()},[user]);
const empName=(id?:string|null)=>employees.find(e=>e.id===id)?.name||'Unassigned';const logout=async()=>{await signOut().catch(()=>{});navigate('/')};if(loading||dataLoading)return <div className="portal-loading"><div className="portal-spinner"/><p>Loading manager portal...</p></div>;
const nav:[Tab,string,any,string?][]=[['overview','Operations',UserCheck],['jobs','Job Assignment',CheckCircle2,'appointments.manage'],['schedule','Team Schedule',CalendarDays,'schedule.manage'],['timecards','Timecards',Clock3,'timecards.manage'],['recruiting','Recruiting',BriefcaseBusiness,'recruiting.manage'],['leads','Leads',Target,'leads.view_all'],['tasks','Tasks',CheckCircle2,'tasks.view_all'],['inventory','Inventory',PackageSearch,'inventory.view'],['finance','Finance',DollarSign,'finance.view']];const visible=nav.filter(n=>!n[3]||can(profile,n[3]));
return <div className="portal-layout"><aside className={`portal-sidebar ${sidebar?'sidebar-open':''}`}><div className="sidebar-header"><Link to="/" className="sidebar-brand"><div className="brand-mark brand-mark-sm">NS</div><div><strong>MANAGER</strong><small>NORTH SPLASH</small></div></Link><button className="sidebar-close" onClick={()=>setSidebar(false)}><X size={18}/></button></div><div className="sidebar-user"><div className="sidebar-avatar">M</div><div><p>{profile?.full_name||'Manager'}</p><span>{profile?.portal_role}</span></div></div><nav className="sidebar-nav">{visible.map(([id,label,Icon])=><button key={id} className={`sidebar-item ${tab===id?'sidebar-active':''}`} onClick={()=>{setTab(id);setSidebar(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-footer"><button className="sidebar-item sidebar-signout" onClick={logout}><LogOut size={18}/>Sign Out</button></div></aside>{sidebar&&<div className="sidebar-backdrop" onClick={()=>setSidebar(false)}/>}<main className="portal-main"><div className="portal-topbar"><button className="sidebar-toggle" onClick={()=>setSidebar(true)}><Menu size={20}/></button><h1>{visible.find(n=>n[0]===tab)?.[1]||'Manager Portal'}</h1></div><div className="portal-content">
{tab==='overview'&&<div className="tab-content"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}><Metric label="Today's Jobs" value={String(appointments.filter(a=>a.scheduled_at?.slice(0,10)===new Date().toISOString().slice(0,10)&&a.status!=='cancelled').length)}/><Metric label="Team" value={String(employees.filter(e=>e.status==='active').length)}/><Metric label="Open Leads" value={String(leads.filter(l=>!['sold','lost','not_interested'].includes(l.status)).length)}/><Metric label="Open Tasks" value={String(tasks.filter(t=>t.status!=='completed').length)}/></div></div>}
{tab==='jobs'&&<div className="tab-content"><div style={{display:'grid',gap:12}}>{appointments.filter(a=>a.status!=='cancelled'&&!a.archived).map(a=><div style={card} key={a.id}><div style={{display:'flex',justifyContent:'space-between'}}><div><strong>{a.service_name}</strong><p>{money(a.price)} · {dt(a.scheduled_at)}</p></div><select value={a.status} onChange={async e=>{const status=e.target.value;await supabase.from('appointments').update({status}).eq('id',a.id);setAppointments(p=>p.map(x=>x.id===a.id?{...x,status:status as any}:x));}}><option>pending</option><option>confirmed</option><option>in_progress</option><option>completed</option><option>cancelled</option></select></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><select value={a.assigned_employee_id||''} onChange={async e=>{const v=e.target.value||null;await supabase.from('appointments').update({assigned_employee_id:v}).eq('id',a.id);setAppointments(p=>p.map(x=>x.id===a.id?{...x,assigned_employee_id:v}:x));}}><option value="">Assign detailer</option>{employees.filter(e=>e.role==='detailer').map(e=><option value={e.id} key={e.id}>{e.name} · L{e.employment_level||1}</option>)}</select><select value={a.assigned_manager_id||''} onChange={async e=>{const v=e.target.value||null;await supabase.from('appointments').update({assigned_manager_id:v}).eq('id',a.id);setAppointments(p=>p.map(x=>x.id===a.id?{...x,assigned_manager_id:v}:x));}}><option value="">Assign manager</option>{employees.filter(e=>e.role==='manager').map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></div></div>)}</div></div>}
{tab==='schedule'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{shifts.map(s=><div style={card} key={s.id}><strong>{empName(s.employee_id)}</strong><p>{s.shift_date} · {s.start_time?.slice(0,5)}–{s.end_time?.slice(0,5)}</p></div>)}</div></div>}
{tab==='timecards'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{times.map(t=><div style={card} key={t.id}><strong>{empName(t.employee_id)}</strong><p>{dt(t.clock_in)} → {dt(t.clock_out)}</p><div><button className="btn-sm btn-primary" onClick={async()=>{await supabase.from('time_entries').update({status:'approved',approved_at:new Date().toISOString()}).eq('id',t.id);setTimes(p=>p.map(x=>x.id===t.id?{...x,status:'approved'}:x));}}>Approve</button> <span>{t.status}</span></div></div>)}</div></div>}
{tab==='recruiting'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{candidates.map(c=><div style={card} key={c.id}><strong>{c.full_name}</strong><p>{c.position.replaceAll('_',' ')} · {c.stage.replaceAll('_',' ')}</p><select value={c.stage} onChange={async e=>{const stage=e.target.value;await supabase.from('recruiting_candidates').update({stage}).eq('id',c.id);setCandidates(p=>p.map(x=>x.id===c.id?{...x,stage}:x));}}><option>applied</option><option>review</option><option>first_interview_pending</option><option>second_interview_pending</option><option>background_check</option><option>job_offer_pending</option><option>offer_accepted</option><option>scheduled_to_start</option><option>employed</option><option>rejected</option></select></div>)}</div></div>}
{tab==='leads'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{leads.map(l=><div style={card} key={l.id}><strong>{l.customer_name||l.address||'Lead'}</strong><p>{empName(l.assigned_employee_id)} · {l.status.replaceAll('_',' ')} · {money(Number(l.estimated_value||0))}</p></div>)}</div></div>}
{tab==='tasks'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{tasks.map(t=><div style={card} key={t.id}><strong>{t.title}</strong><p>{empName(t.assigned_employee_id)} · {t.status}</p></div>)}</div></div>}
{tab==='inventory'&&<div className="tab-content"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{inventory.map(i=><div style={card} key={i.id}><strong>{i.name}</strong><p>{i.quantity} on hand · Reorder at {i.reorder_level}</p>{Number(i.quantity)<=Number(i.reorder_level)&&<span style={{color:'#df8a8a'}}>Low stock</span>}</div>)}</div></div>}
{tab==='finance'&&<div className="tab-content"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}><Metric label="Collected Revenue" value={money(payments.filter(p=>p.status==='completed').reduce((s,p)=>s+Number(p.amount),0))}/><Metric label="Expenses" value={money(expenses.reduce((s,e)=>s+Number(e.amount),0))}/><Metric label="Net Before Payroll/Tax" value={money(payments.filter(p=>p.status==='completed').reduce((s,p)=>s+Number(p.amount),0)-expenses.reduce((s,e)=>s+Number(e.amount),0))}/></div></div>}
</div></main></div>}
function Metric({label,value}:{label:string;value:string}){return <div style={card}><span style={{color:'#888'}}>{label}</span><h2>{value}</h2></div>}
