import { useEffect, useRef, useState } from 'react';
import type { Lead, LeadTerritory } from '@/lib/supabase';

type Door = { id?: string; latitude:number; longitude:number; address?:string|null; status?:string; territory_id?:string|null; lead_id?:string|null };
type Props={territories:LeadTerritory[];leads?:Lead[];doors?:Door[];editable?:boolean;selectedTerritoryId?:string;onPolygonChange?:(points:[number,number][])=>void;onDoorClick?:(door:Door)=>void;onMapClick?:(lat:number,lng:number)=>void;};
const statusColor=(s?:string)=>({sold:'#2f9e62',completed:'#2f9e62',appointment_set:'#c9a96e',interested:'#4776d0',follow_up:'#4776d0',not_home:'#d9a441',no_answer:'#d9a441',cancelled:'#b05b5b',customer_cancelled:'#b05b5b',company_cancelled:'#8d4d4d',no_show:'#b05b5b',do_not_knock:'#111',not_interested:'#b05b5b'} as Record<string,string>)[s||'']||'#777';
export default function FieldTerritoryMap({territories,leads=[],doors=[],editable=false,selectedTerritoryId,onPolygonChange,onDoorClick,onMapClick}:Props){
 const el=useRef<HTMLDivElement|null>(null), map=useRef<any>(null), layer=useRef<any>(null), draw=useRef<any>(null); const points=useRef<[number,number][]>([]); const [ready,setReady]=useState(false);
 useEffect(()=>{(async()=>{if(!document.querySelector('link[data-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='true';document.head.appendChild(l)}if(!(window as any).L)await new Promise<void>((res,rej)=>{const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=()=>res();s.onerror=rej;document.body.appendChild(s)});setReady(true)})()},[]);
 useEffect(()=>{if(!ready||!el.current||map.current)return;const L=(window as any).L;const m=L.map(el.current,{zoomControl:true}).setView([35.7796,-78.6382],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap'}).addTo(m);layer.current=L.layerGroup().addTo(m);draw.current=L.layerGroup().addTo(m);m.on('click',(e:any)=>{if(editable){points.current=[...points.current,[e.latlng.lat,e.latlng.lng]];draw.current.clearLayers();if(points.current.length>1)L.polyline(points.current,{color:'#c9a96e',weight:3}).addTo(draw.current);points.current.forEach(p=>L.circleMarker(p,{radius:5,color:'#c9a96e',fillOpacity:1}).addTo(draw.current));onPolygonChange?.(points.current)}else onMapClick?.(e.latlng.lat,e.latlng.lng)});map.current=m;setTimeout(()=>m.invalidateSize(),100);return()=>{m.remove();map.current=null}},[ready,editable]);
 useEffect(()=>{if(!map.current||!layer.current)return;const L=(window as any).L;layer.current.clearLayers();let bounds:any[]=[];territories.forEach(t=>{const poly=(t.polygon_geojson as any)?.coordinates?.[0];if(poly?.length){const pts=poly.map((p:number[])=>[p[1],p[0]]);L.polygon(pts,{color:'#c9a96e',weight:t.id===selectedTerritoryId?4:2,fillOpacity:.08}).bindTooltip(t.name).addTo(layer.current);bounds.push(...pts)}else if(t.center_lat!=null&&t.center_lng!=null){L.circle([Number(t.center_lat),Number(t.center_lng)],{radius:t.radius_meters,color:'#c9a96e',weight:2,fillOpacity:.05}).bindTooltip(t.name).addTo(layer.current)}});doors.forEach(d=>{const c=statusColor(d.status);L.circleMarker([d.latitude,d.longitude],{radius:7,color:c,fillColor:c,fillOpacity:.95,weight:2}).on('click',()=>onDoorClick?.(d)).bindTooltip(d.address||'House').addTo(layer.current);bounds.push([d.latitude,d.longitude])});leads.forEach(l=>{if(l.latitude==null||l.longitude==null)return;const c=statusColor(l.status);L.circleMarker([Number(l.latitude),Number(l.longitude)],{radius:8,color:'#fff',weight:1,fillColor:c,fillOpacity:1}).on('click',()=>onDoorClick?.({latitude:Number(l.latitude),longitude:Number(l.longitude),address:l.address,status:l.status,territory_id:l.territory_id,lead_id:l.id})).bindTooltip(l.address||l.customer_name||'Lead').addTo(layer.current);bounds.push([Number(l.latitude),Number(l.longitude)])});if(bounds.length&&bounds.length<500)try{map.current.fitBounds(bounds,{padding:[25,25],maxZoom:17})}catch{}},[territories,leads,doors,selectedTerritoryId,onDoorClick]);
 const reset=()=>{points.current=[];draw.current?.clearLayers();onPolygonChange?.([])};
 return <div className="field-map-wrap"><div ref={el} className="field-map-canvas"/>{editable&&<div className="field-map-tools"><span>Click around the neighborhood to draw the boundary.</span><button type="button" className="btn-sm btn-outline" onClick={reset}>Clear drawing</button></div>}</div>
}
