import { useEffect,useMemo,useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { Clock3,LogOut,MapPin,Menu,Navigation,Plus,Target,TrendingUp,X,ChevronDown } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth'; import { signOut } from '@/lib/auth'; import { supabase } from '@/lib/supabase';
import type { Employee,Lead,LeadTerritory,SalesRecord,TimeEntry,TerritoryDoor } from '@/lib/supabase'; import { money } from '@/lib/data'; import FieldTerritoryMap from '@/components/FieldTerritoryMap';
type Tab='map'|'leads'|'followups'|'sales'|'timeclock'; const card:React.CSSProperties={background:'#111',color:'#fff',border:'1px solid #292929',borderRadius:14,padding:20};
const STATUS=[['new','New'],['not_home','Not Home / Revisit'],['interested','Interested'],['follow_up','Follow Up'],['appointment_set','Appointment Set'],['sold','Sold'],['not_interested','Not Interested'],['do_not_knock','Do Not Knock']] as const;
export default function D2DPortal(){const {user,profile,loading}=useAuth();const navigate=useNavigate();const [tab,setTab]=useState<Tab>('map'),[sidebar,setSidebar]=useState(false),[employee,setEmployee]=useState<Employee|null>(null),[leads,setLeads]=useState<Lead[]>([]),[territories,setTerritories]=useState<LeadTerritory[]>([]),[doors,setDoors]=useState<TerritoryDoor[]>([]),[sales,setSales]=useState<SalesRecord[]>([]),[times,setTimes]=useState<TimeEntry[]>([]),[busy,setBusy]=useState(true),[selectedDoor,setSelectedDoor]=useState<Partial<TerritoryDoor>&{lead_id?:string|null}|null>(null),[manual,setManual]=useState(false),[group,setGroup]=useState<Record<string,boolean>>({field:true,account:true});const [form,setForm]=useState({customer_name:'',address:'',phone:'',email:'',status:'new',service_interest:'',vehicle_info:'',estimated_value:'',follow_up_at:'',notes:''});
useEffect(()=>{if(!loading&&(!user||!['d2d','owner'].includes(profile?.portal_role||'')))navigate('/portal')},[user,profile,loading,navigate]);
const load=async()=>{if(!user)return;const {data:emp}=await supabase.from('employees').select('*').eq('user_id',user.id).maybeSingle();setEmployee(emp);if(!emp){setBusy(false);return}const [l,t,s,ti]=await Promise.all([supabase.from('leads').select('*').eq('assigned_employee_id',emp.id).order('created_at',{ascending:false}),supabase.from('lead_territories').select('*').eq('assigned_employee_id',emp.id),supabase.from('sales_records').select('*').eq('employee_id',emp.id).order('sold_at',{ascending:false}),supabase.from('time_entries').select('*').eq('employee_id',emp.id).order('clock_in',{ascending:false})]);setLeads(l.data??[]);setTerritories(t.data??[]);setSales(s.data??[]);setTimes(ti.data??[]);const ids=(t.data??[]).map(x=>x.id);if(ids.length){const d=await supabase.from('territory_doors').select('*').in('territory_id',ids);setDoors(d.data??[])}setBusy(false)};useEffect(()=>{load()},[user]);
const pickDoor=(d:any)=>{const lead=d.lead_id?leads.find(l=>l.id===d.lead_id):null;setSelectedDoor(d);setManual(false);setForm({customer_name:lead?.customer_name||'',address:lead?.address||d.address||'',phone:lead?.phone||'',email:lead?.email||'',status:lead?.status||d.status||'new',service_interest:lead?.service_interest||'',vehicle_info:lead?.vehicle_info||'',estimated_value:String(lead?.estimated_value||''),follow_up_at:lead?.follow_up_at?.slice(0,16)||'',notes:lead?.notes||d.notes||''})};
const saveLead=async(e:React.FormEvent)=>{e.preventDefault();if(!employee)return;const territory_id=selectedDoor?.territory_id||territories[0]?.id||null;const payload={...form,assigned_employee_id:employee.id,territory_id,latitude:selectedDoor?.latitude??null,longitude:selectedDoor?.longitude??null,estimated_value:Number(form.estimated_value||0),follow_up_at:form.follow_up_at?new Date(form.follow_up_at).toISOString():null,last_contacted_at:new Date().toISOString()};let lead:any;if(selectedDoor?.lead_id){const r=await supabase.from('leads').update(payload).eq('id',selectedDoor.lead_id).select().single();if(r.error)return alert(r.error.message);lead=r.data;setLeads(p=>p.map(x=>x.id===lead.id?lead:x))}else{const r=await supabase.from('leads').insert(payload).select().single();if(r.error)return alert(r.error.message);lead=r.data;setLeads(p=>[lead,...p])}if(selectedDoor?.id){await supabase.from('territory_doors').update({lead_id:lead.id,status:form.status,last_visited_at:new Date().toISOString(),last_employee_id:employee.id,notes:form.notes}).eq('id',selectedDoor.id);setDoors(p=>p.map(x=>x.id===selectedDoor.id?{...x,lead_id:lead.id,status:form.status}:x))}setSelectedDoor(null);setManual(false)};
const manualLead=()=>{setSelectedDoor({territory_id:null,latitude:undefined,longitude:undefined});setManual(true);setForm({customer_name:'',address:'',phone:'',email:'',status:'new',service_interest:'',vehicle_info:'',estimated_value:'',follow_up_at:'',notes:''})};
const captureLocation=()=>navigator.geolocation.getCurrentPosition(p=>{setSelectedDoor({territory_id:null,latitude:p.coords.latitude,longitude:p.coords.longitude});setManual(true)},()=>alert('Allow location access to pin this lead.'));
const open=times.find(t=>!t.clock_out);const clock=async()=>{if(!employee)return;if(open){const {data}=await supabase.from('time_entries').update({clock_out:new Date().toISOString()}).eq('id',open.id).select().single();if(data)setTimes(p=>p.map(t=>t.id===open.id?data:t))}else{const {data}=await supabase.from('time_entries').insert({employee_id:employee.id,clock_in:new Date().toISOString(),status:'pending'}).select().single();if(data)setTimes(p=>[data,...p])}};
const revenue=useMemo(()=>sales.filter(s=>s.status==='completed').reduce((n,s)=>n+Number(s.sale_amount),0),[sales]);const commission=revenue*Number(employee?.commission_rate||0)/100,base=Number(employee?.weekly_base||0);const logout=async()=>{await signOut().catch(()=>{});navigate('/')};if(loading||busy)return <div className="portal-loading">Loading D2D portal...</div>;if(!employee)return <div className="portal-loading">Your account is not linked to a D2D employee profile yet.</div>;
const nav:[Tab,string,any,string][]=[['map','Territory & Doors',MapPin,'field'],['leads','My Leads',Target,'field'],['followups','Follow-Ups',Navigation,'field'],['sales','Sales & Commission',TrendingUp,'account'],['timeclock','Time Clock',Clock3,'account']];
return <div className="portal-layout"><aside className={`portal-sidebar ${sidebar?'sidebar-open':''}`}><div className="sidebar-header"><Link to="/" className="sidebar-brand"><div className="brand-mark brand-mark-sm">NS</div><div><strong>D2D SALES</strong><small>NORTH SPLASH</small></div></Link><button className="sidebar-close" onClick={()=>setSidebar(false)}><X size={18}/></button></div><div className="sidebar-user"><div className="sidebar-avatar">{employee.name[0]}</div><div><p>{employee.name}</p><span>Level {employee.employment_level||1} · {employee.commission_rate}%</span></div></div><nav className="sidebar-nav">{[['field','Field Work'],['account','My Work']].map(([id,label])=><div className="nav-group" key={id}><button className="nav-group-title" onClick={()=>setGroup(p=>({...p,[id]:!p[id]}))}>{label}<ChevronDown size={15} className={group[id]?'nav-chevron-open':''}/></button>{group[id]&&nav.filter(n=>n[3]===id).map(([tid,l,Icon])=><button key={tid} className={`sidebar-item ${tab===tid?'sidebar-active':''}`} onClick={()=>{setTab(tid);setSidebar(false)}}><Icon size={18}/>{l}</button>)}</div>)}</nav><div className="sidebar-footer"><button className="sidebar-item sidebar-signout" onClick={logout}><LogOut size={18}/>Sign Out</button></div></aside>{sidebar&&<div className="sidebar-backdrop" onClick={()=>setSidebar(false)}/>}<main className="portal-main"><div className="portal-topbar"><button className="sidebar-toggle" onClick={()=>setSidebar(true)}><Menu size={20}/></button><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="portal-content">
{tab==='map'&&<div className="tab-content"><div className="field-map-header"><div><h2>Work Your Territory</h2><p>Tap a house marker to record the result. Manual add stays available for referrals or out-of-territory leads.</p></div><button className="btn-primary" onClick={manualLead}><Plus size={15}/> Manual Lead</button></div><FieldTerritoryMap territories={territories} leads={leads} doors={doors} onDoorClick={pickDoor} onMapClick={(lat,lng)=>{setSelectedDoor({latitude:lat,longitude:lng,territory_id:null});setManual(true)}}/><div className="map-legend"><span>● Unworked</span><span>● Revisit</span><span>● Interested</span><span>● Appointment</span><span>● Sold</span><span>● Do Not Knock</span></div>{(selectedDoor||manual)&&<form className="door-sheet" onSubmit={saveLead}><div className="door-sheet-head"><div><small>{manual?'MANUAL / OUTSIDE TERRITORY':'SELECTED HOUSE'}</small><h3>{form.address||'New Lead'}</h3></div><button type="button" className="icon-btn" onClick={()=>{setSelectedDoor(null);setManual(false)}}><X/></button></div>{manual&&<><button type="button" className="btn-outline btn-full" onClick={captureLocation}><Navigation size={15}/> Use Current Location</button><input required placeholder="Street address" value={form.address} onChange={e=>setForm(p=>({...p,address:e.target.value}))}/></>}<div className="door-form-grid"><input placeholder="Name" value={form.customer_name} onChange={e=>setForm(p=>({...p,customer_name:e.target.value}))}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm(p=>({...p,phone:e.target.value}))}/><input placeholder="Email" value={form.email} onChange={e=>setForm(p=>({...p,email:e.target.value}))}/><input placeholder="Vehicle" value={form.vehicle_info} onChange={e=>setForm(p=>({...p,vehicle_info:e.target.value}))}/><input placeholder="Service interest" value={form.service_interest} onChange={e=>setForm(p=>({...p,service_interest:e.target.value}))}/><input type="number" placeholder="Estimated value" value={form.estimated_value} onChange={e=>setForm(p=>({...p,estimated_value:e.target.value}))}/><select value={form.status} onChange={e=>setForm(p=>({...p,status:e.target.value}))}>{STATUS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="datetime-local" value={form.follow_up_at} onChange={e=>setForm(p=>({...p,follow_up_at:e.target.value}))}/></div><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm(p=>({...p,notes:e.target.value}))}/><button className="btn-primary btn-full">Save House / Lead</button></form>}</div>}
{tab==='leads'&&<div className="tab-content lead-card-grid">{leads.map(l=><button className="lead-card" key={l.id} onClick={()=>pickDoor({lead_id:l.id,latitude:Number(l.latitude||0),longitude:Number(l.longitude||0),address:l.address,territory_id:l.territory_id,status:l.status})}><strong>{l.address||l.customer_name||'Lead'}</strong><span>{l.status.replaceAll('_',' ')} · {money(Number(l.estimated_value||0))}</span></button>)}</div>}
{tab==='followups'&&<div className="tab-content lead-card-grid">{leads.filter(l=>l.follow_up_at||l.status==='follow_up').map(l=><div style={card} key={l.id}><strong>{l.customer_name||l.address}</strong><p>{l.follow_up_at?new Date(l.follow_up_at).toLocaleString():'Follow up needed'}</p></div>)}</div>}
{tab==='sales'&&<div className="tab-content"><div className="metric-grid"><div style={card}><span>Completed Revenue</span><h2>{money(revenue)}</h2></div><div style={card}><span>Commission</span><h2>{money(commission)}</h2></div><div style={card}><span>Weekly Base</span><h2>{money(base)}</h2></div><div style={card}><span>Estimated Weekly Pay</span><h2>{money(base+commission)}</h2></div></div></div>}
{tab==='timeclock'&&<div className="tab-content"><div style={{...card,maxWidth:560}}><h2>{open?'Clocked In':'Ready to Work?'}</h2><button className="btn-primary btn-full" onClick={clock}>{open?'Clock Out':'Clock In'}</button></div></div>}
</div></main></div>}
