import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Clock3, DollarSign, LogOut, MapPin, Menu, Navigation, Plus, Target, TrendingUp, X } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { signOut } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import type { Employee, Lead, LeadTerritory, SalesRecord, TimeEntry } from '@/lib/supabase';
import { money } from '@/lib/data';

type Tab='map'|'leads'|'followups'|'sales'|'timeclock';
const card:React.CSSProperties={background:'#111',border:'1px solid #292929',borderRadius:14,padding:20};
const STATUS=[['new','New'],['not_home','Not Home'],['no_answer','No Answer'],['interested','Interested'],['follow_up','Follow Up'],['appointment_set','Appointment Set'],['estimate_sent','Estimate Sent'],['sold','Sold'],['not_interested','Not Interested'],['do_not_knock','Do Not Knock'],['existing_customer','Existing Customer'],['bad_address','Bad Address'],['lost','Lost']] as const;
const dt=(v?:string|null)=>v?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';

function D2DMap({leads,territories,onPoint}:{leads:Lead[];territories:LeadTerritory[];onPoint:(lat:number,lng:number)=>void}){const el=useRef<HTMLDivElement|null>(null);const map=useRef<any>(null);const layers=useRef<any>(null);const [ready,setReady]=useState(false);useEffect(()=>{(async()=>{if(!document.querySelector('link[data-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='true';document.head.appendChild(l)}if(!(window as any).L)await new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=()=>resolve();s.onerror=()=>reject();document.body.appendChild(s)});setReady(true)})()},[]);useEffect(()=>{if(!ready||!el.current||map.current)return;const L=(window as any).L;const m=L.map(el.current).setView([35.7796,-78.6382],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(m);layers.current=L.layerGroup().addTo(m);m.on('click',(e:any)=>onPoint(e.latlng.lat,e.latlng.lng));map.current=m;setTimeout(()=>m.invalidateSize(),100);return()=>{m.remove();map.current=null}},[ready,onPoint]);useEffect(()=>{if(!map.current||!layers.current)return;const L=(window as any).L;layers.current.clearLayers();territories.forEach(t=>{if(t.center_lat!=null&&t.center_lng!=null)L.circle([Number(t.center_lat),Number(t.center_lng)],{radius:t.radius_meters,color:'#c9a96e',weight:2,fillOpacity:.05}).bindPopup(t.name).addTo(layers.current)});leads.forEach(l=>{if(l.latitude!=null&&l.longitude!=null){const color=l.status==='sold'?'#35b36b':['not_interested','do_not_knock','lost'].includes(l.status)?'#b94d4d':'#c9a96e';L.circleMarker([Number(l.latitude),Number(l.longitude)],{radius:7,color,fillColor:color,fillOpacity:.9}).bindPopup(`<strong>${l.customer_name||'Lead'}</strong><br>${l.address||''}<br>${l.status.replaceAll('_',' ')}`).addTo(layers.current)}})},[leads,territories,ready]);return <div ref={el} style={{height:520,borderRadius:14,overflow:'hidden',border:'1px solid #292929'}}/>}

export default function D2DPortal(){const {user,profile,loading}=useAuth();const navigate=useNavigate();const [tab,setTab]=useState<Tab>('map');const [sidebar,setSidebar]=useState(false);const [employee,setEmployee]=useState<Employee|null>(null);const [leads,setLeads]=useState<Lead[]>([]);const [territories,setTerritories]=useState<LeadTerritory[]>([]);const [sales,setSales]=useState<SalesRecord[]>([]);const [times,setTimes]=useState<TimeEntry[]>([]);const [dataLoading,setDataLoading]=useState(true);const [form,setForm]=useState({customer_name:'',address:'',phone:'',email:'',latitude:'',longitude:'',status:'new',service_interest:'',vehicle_info:'',estimated_value:'',follow_up_at:'',territory_id:'',notes:''});
useEffect(()=>{if(!loading&&(!user||!['d2d','owner'].includes(profile?.portal_role||'')))navigate('/portal')},[user,profile,loading,navigate]);
useEffect(()=>{if(!user)return;(async()=>{const {data:emp}=await supabase.from('employees').select('*').eq('user_id',user.id).maybeSingle();setEmployee(emp);if(!emp){setDataLoading(false);return}const [l,t,s,ti]=await Promise.all([supabase.from('leads').select('*').eq('assigned_employee_id',emp.id).order('created_at',{ascending:false}),supabase.from('lead_territories').select('*').eq('assigned_employee_id',emp.id),supabase.from('sales_records').select('*').eq('employee_id',emp.id).order('sold_at',{ascending:false}),supabase.from('time_entries').select('*').eq('employee_id',emp.id).order('clock_in',{ascending:false})]);setLeads(l.data??[]);setTerritories(t.data??[]);setSales(s.data??[]);setTimes(ti.data??[]);setDataLoading(false)})()},[user]);
const addLead=async(e:React.FormEvent)=>{e.preventDefault();if(!employee)return;const {data,error}=await supabase.from('leads').insert({...form,assigned_employee_id:employee.id,territory_id:form.territory_id||territories[0]?.id||null,latitude:form.latitude?Number(form.latitude):null,longitude:form.longitude?Number(form.longitude):null,estimated_value:Number(form.estimated_value||0),follow_up_at:form.follow_up_at?new Date(form.follow_up_at).toISOString():null}).select().single();if(error)return alert(error.message);setLeads(p=>[data,...p]);setForm(p=>({...p,customer_name:'',address:'',phone:'',email:'',service_interest:'',vehicle_info:'',estimated_value:'',follow_up_at:'',notes:''}))};
const captureLocation=()=>{if(!employee)return;navigator.geolocation.getCurrentPosition(async pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;setForm(p=>({...p,latitude:lat.toFixed(6),longitude:lng.toFixed(6)}));await supabase.from('rep_locations').insert({employee_id:employee.id,latitude:lat,longitude:lng,accuracy_meters:pos.coords.accuracy})},()=>alert('Location permission is required for GPS check-in.'))};
const updateStatus=async(lead:Lead,status:string)=>{await supabase.from('leads').update({status,last_contacted_at:new Date().toISOString(),updated_at:new Date().toISOString(),...(status==='sold'?{actual_sale_amount:lead.actual_sale_amount||lead.estimated_value}:{})}).eq('id',lead.id);await supabase.from('lead_activities').insert({lead_id:lead.id,employee_id:employee?.id,activity_type:'status_change',previous_status:lead.status,new_status:status});setLeads(p=>p.map(l=>l.id===lead.id?{...l,status}:l))};
const open=times.find(t=>!t.clock_out);const clock=async()=>{if(!employee)return;if(open){const {data}=await supabase.from('time_entries').update({clock_out:new Date().toISOString()}).eq('id',open.id).select().single();if(data)setTimes(p=>p.map(t=>t.id===open.id?data:t))}else{const {data}=await supabase.from('time_entries').insert({employee_id:employee.id,clock_in:new Date().toISOString(),status:'pending'}).select().single();if(data)setTimes(p=>[data,...p])}};
const completedSales=sales.filter(s=>s.status==='completed');const revenue=completedSales.reduce((s,r)=>s+Number(r.sale_amount),0);const commission=revenue*(Number(employee?.commission_rate||0)/100);const base=Number(employee?.weekly_base||0);const logout=async()=>{await signOut().catch(()=>{});navigate('/')};if(loading||dataLoading)return <div className="portal-loading"><div className="portal-spinner"/><p>Loading D2D portal...</p></div>;if(!employee)return <div className="portal-loading"><p>Your account is not linked to a D2D employee profile yet.</p></div>;
const nav:[Tab,string,any][]=[['map','Territory Map',MapPin],['leads','My Leads',Target],['followups','Follow-Ups',Navigation],['sales','Sales & Commission',TrendingUp],['timeclock','Time Clock',Clock3]];
return <div className="portal-layout"><aside className={`portal-sidebar ${sidebar?'sidebar-open':''}`}><div className="sidebar-header"><Link to="/" className="sidebar-brand"><div className="brand-mark brand-mark-sm">NS</div><div><strong>D2D SALES</strong><small>NORTH SPLASH</small></div></Link><button className="sidebar-close" onClick={()=>setSidebar(false)}><X size={18}/></button></div><div className="sidebar-user"><div className="sidebar-avatar">{employee.name[0]}</div><div><p>{employee.name}</p><span>Level {employee.employment_level||1} · {employee.commission_rate}%</span></div></div><nav className="sidebar-nav">{nav.map(([id,label,Icon])=><button key={id} className={`sidebar-item ${tab===id?'sidebar-active':''}`} onClick={()=>{setTab(id);setSidebar(false)}}><Icon size={18}/>{label}</button>)}</nav><div className="sidebar-footer"><button className="sidebar-item sidebar-signout" onClick={logout}><LogOut size={18}/>Sign Out</button></div></aside>{sidebar&&<div className="sidebar-backdrop" onClick={()=>setSidebar(false)}/>}<main className="portal-main"><div className="portal-topbar"><button className="sidebar-toggle" onClick={()=>setSidebar(true)}><Menu size={20}/></button><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="portal-content">
{tab==='map'&&<div className="tab-content"><div style={{display:'grid',gridTemplateColumns:'minmax(0,1.35fr) minmax(320px,.65fr)',gap:18}}><div><D2DMap leads={leads} territories={territories} onPoint={(lat,lng)=>setForm(p=>({...p,latitude:lat.toFixed(6),longitude:lng.toFixed(6)}))}/><button className="btn-outline" style={{marginTop:10}} onClick={captureLocation}><Navigation size={15}/> Use My Current Location</button></div><form style={card} onSubmit={addLead}><h3>Add Door / Lead</h3><button type="button" className="btn-outline btn-full" onClick={captureLocation}>Use GPS Location</button><input placeholder="Name" value={form.customer_name} onChange={e=>setForm(p=>({...p,customer_name:e.target.value}))}/><input placeholder="Street address" value={form.address} onChange={e=>setForm(p=>({...p,address:e.target.value}))}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm(p=>({...p,phone:e.target.value}))}/><input placeholder="Service interest" value={form.service_interest} onChange={e=>setForm(p=>({...p,service_interest:e.target.value}))}/><input type="number" placeholder="Estimated value" value={form.estimated_value} onChange={e=>setForm(p=>({...p,estimated_value:e.target.value}))}/><select value={form.status} onChange={e=>setForm(p=>({...p,status:e.target.value}))}>{STATUS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="datetime-local" value={form.follow_up_at} onChange={e=>setForm(p=>({...p,follow_up_at:e.target.value}))}/><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm(p=>({...p,notes:e.target.value}))}/><button className="btn-primary btn-full"><Plus size={15}/>Save Lead</button></form></div></div>}
{tab==='leads'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{leads.map(l=><div style={card} key={l.id}><div style={{display:'flex',justifyContent:'space-between'}}><div><strong>{l.customer_name||l.address||'Lead'}</strong><p>{l.address} · {l.service_interest}</p></div><strong>{money(Number(l.actual_sale_amount||l.estimated_value||0))}</strong></div><select value={l.status} onChange={e=>updateStatus(l,e.target.value)}>{STATUS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></div>)}</div></div>}
{tab==='followups'&&<div className="tab-content"><div style={{display:'grid',gap:10}}>{leads.filter(l=>l.follow_up_at&& !['sold','lost','not_interested'].includes(l.status)).sort((a,b)=>new Date(a.follow_up_at!).getTime()-new Date(b.follow_up_at!).getTime()).map(l=><div style={card} key={l.id}><strong>{l.customer_name||l.address}</strong><p>Follow up {dt(l.follow_up_at)}</p><span>{l.phone}</span></div>)}</div></div>}
{tab==='sales'&&<div className="tab-content"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}><Metric label="Completed Revenue" value={money(revenue)}/><Metric label="Commission" value={money(commission)}/><Metric label="Weekly Base" value={money(base)}/><Metric label="Estimated Weekly Pay" value={money(base+commission)}/></div><p style={{color:'#888'}}>Commission is estimated from completed/collected sales; owner payroll approval controls final pay.</p></div>}
{tab==='timeclock'&&<div className="tab-content"><div style={{...card,maxWidth:560}}><h2>{open?'Clocked In':'Ready to start?'}</h2>{open&&<p>Started {dt(open.clock_in)}</p>}<button className="btn-primary btn-full" onClick={clock}>{open?'Clock Out':'Clock In'}</button></div></div>}
</div></main></div>}
function Metric({label,value}:{label:string;value:string}){return <div style={card}><span style={{color:'#888'}}>{label}</span><h2>{value}</h2></div>}
